---
services:
  app:
    build: .
    environment:
      SERVICE_PORT: 8000
      SERVICE_DB_PORT: 5432
      SERVICE_DB_HOST: postgres
      SERVICE_DB_USER: tabeo
      SERVICE_DB_PASS: tabeo
      SERVICE_DB_NAME: tabeo
      SERVICE_DB_SSL_MODE: disable
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: "postgres:14"
    restart: always
    environment:
      POSTGRES_PASSWORD: tabeo
      POSTGRES_USER: tabeo
      PGUSER: tabeo
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  mongodata:
